### ISSUE TITLE
Missing OpenCritic/Game Length

### ISSUE THREAD

**Issue by tejapoth** [GamerKingFaiz/shouldiplay#10]
Hi Faiz, I will use this to occasionally update games that I find which are missing Opencritic or Game length!

Right now | missing Opencritic:
- Travis Strikes Again: No More Heroes - https://opencritic.com/game/7117/travis-strikes-again-no-more-heroes 
> Should I play this - https://shouldiplaythis.com/?page=1&search=Travis%20Strikes%20Again:%20No%20More%20Heroes

There are 2 versions of Travis Strikes Again: No More Heroes  one is complete edition and other is original and they both have opencritic. 
Regular version - https://opencritic.com/game/7117/travis-strikes-again-no-more-heroes
Complete Edition - https://opencritic.com/game/8500/travis-strikes-again-no-more-heroes-complete-edition

SIPT only shows Opencritic for Complete edition and not for regular version. Cheers!

**Comment by GamerKingFaiz** [comment]
Thanks, fixed!

**Comment by tejapoth** [comment]
Hello again, Dead Space (Remake) opencritic is not coming up on SIPL unfortunately.
https://shouldiplaythis.com/?page=1&search=Dead%20Space
OC link: https://opencritic.com/game/13897/dead-space-remake-

Cheers!

**Comment by GamerKingFaiz** [comment]
Ah unfortunately for this one HLTB kept the name the same as the original, so if I fix it to match the original will also pick up the remaster's OC score. I'll have to see if I can put in some year matching logic in the future to help with cases like this.

**Comment by tejapoth** [comment]
ooh okay. so i guess in ur code there’s no way to do a one off manual assignment of opencritic to one particular game on HLTB? or is everything automated in your code?
 But all good, that would be great actually to implement a year system cos I noticed some games had high opencritic before i realised it was for the original version and not the remake!

**Comment by tejapoth** [comment]
Hi again,
Lego DC Super Villains is missing OC
https://shouldiplaythis.com/?page=1&search=Lego%20DC%20Super-Villains
https://opencritic.com/game/6742/lego-dc-super-villains
Cheers!

**Comment by GamerKingFaiz** [comment]
Fixed, thanks!

**Comment by tejapoth** [comment]
Hi again,
AI: The Somnium Files - nirvanA Initiative is missing OC
https://shouldiplaythis.com/?page=1&search=AI:%20THE%20SOMNIUM%20FILES%20-%20nirvanA%20Initiative
https://opencritic.com/game/13265/ai-the-somnium-files-nirvana-initiative
Cheers!

**Comment by GamerKingFaiz** [comment]
Fixed 👍🏼

**Comment by tejapoth** [comment]
Hello some more bugs for you. I decided to wait for a few games before I suggest bugs. So i have a few games to report so here i am!
Missing OC:
Persona 4 Golden : https://shouldiplaythis.com/?page=1&search=Persona%204%20Golden 
https://opencritic.com/game/9636/persona-4-golden
Xenoblade Chronicles : https://shouldiplaythis.com/?page=1&search=Xenoblade%20Chronicles 
https://opencritic.com/game/9261/xenoblade-chronicles-definitive-edition
Life is Strange : https://shouldiplaythis.com/?page=1&search=Life%20Is%20Strange
https://opencritic.com/game/1995/life-is-strange-season-one

Single player Games listed as Co-Op on SIPT but HLTB only has  “Main Story, + Extras , Complete” there can’t see time 
Mario + Rabbids Kingdom Battle - Donkey Kong Adventure
https://shouldiplaythis.com/?page=1&search=Mario%20+%20Rabbids%20Kingdom%20Battle%20-%20Donkey%20Kong%20Adventure
Bloodborne: The Old Hunters
https://shouldiplaythis.com/?page=1&search=Bloodborne%20old

Cheers!

**Comment by GamerKingFaiz** [comment]
Thanks for all the reports!

I've fixed all the missing OC data.

And for the last two, HLTB has them classified as DLC. So I included DLC in the logic to display as a normal game (vs a multiplayer game). Those two and all other DLCs should be fixed!

**Comment by tejapoth** [comment]
Fantastic stuff buddy thanks!

**Comment by tejapoth** [comment]
Hello buddy more bugs for you.

Missing OC: 
[The Dark Pictures: House of Ashes](https://howlongtobeat.com/game/84604) - https://opencritic.com/game/12206/the-dark-pictures-anthology-house-of-ashes
[The Dark Pictures: Little Hope](https://howlongtobeat.com/game/70075) - https://opencritic.com/game/10436/the-dark-pictures-anthology-little-hope
[The Dark Pictures: The Devil in Me](https://howlongtobeat.com/game/99440) - https://opencritic.com/game/13688/the-dark-pictures-anthology-the-devil-in-me
[Chivalry II](https://howlongtobeat.com/game/69351) - https://opencritic.com/game/11293/chivalry-2
[Duke Nukem 3D: 20th Anniversary World Tour](https://howlongtobeat.com/game/40470) - https://opencritic.com/game/3259/duke-nukem-3d-world-tour-20th-anniversary-edition
[Hitman GO](https://howlongtobeat.com/game/18017) - https://opencritic.com/game/2325/hitman-go-definitive-edition
[Star Wars: Battlefront II](https://howlongtobeat.com/game/45153) - https://opencritic.com/game/4507/star-wars-battlefront-2
[Ni no Kuni: Wrath of the White Witch](https://howlongtobeat.com/game/6585) - https://opencritic.com/game/8270/ni-no-kuni-wrath-of-the-white-witch-remastered
[Dead Space](https://howlongtobeat.com/game/95927) - https://opencritic.com/game/13897/dead-space-remake-
[System Shock](https://howlongtobeat.com/game/74181) - https://opencritic.com/game/14989/system-shock-2023-remake-

Issues with ‘ in Luigi’s Mansion where nothing pops up until you type “Luigis Mansion” without apostrophes. Other examples:
Zelda Link’s Awakening
https://shouldiplaythis.com/?page=1&search=luigi%E2%80%99s%20mansion
https://shouldiplaythis.com/?page=1&search=zelda%20link%E2%80%99s%20awakening

Cheers!

**Comment by GamerKingFaiz** [comment]
> Missing OC:

Thanks for the reports! These are all fixed.

> Issues with ‘ in Luigi’s Mansion where nothing pops up until you type “Luigis Mansion” without apostrophes.

Took me a little bit to figure out what was going on here, but I found that you're actually using a [right single quote](https://en.wikipedia.org/wiki/Right_single_quotation_mark) instead of a straight apostrophe. They look very similar, but you might be able to see the difference if you zoom in:

```
Right Single Quotation Mark:    ’
Straight Apostrophe:            '
```

I can't even type a right single quote on my keyboard, so I'm not sure how you're typing it. Perhaps you have a different keyboard layout. I would suggest you find the straight apostrophe on your keyboard and use that instead. If you use the right single quote directly on HLTB's site, you'll see it doesn't work there either (no results are returned).

**Comment by tejapoth** [comment]
> Thanks for the reports! These are all fixed.

Awesome except one! Duke Nukem 3D is not fixed yet - 
https://shouldiplaythis.com/?page=1&search=Duke%20Nukem%203D:%2020th%20Anniversary%20World%20Tour - https://opencritic.com/game/3259/duke-nukem-3d-world-tour-20th-anniversary-edition

> Right Single Quotation Mark:    ’
> Straight Apostrophe:            ' 

Yeah that’s exactly what i suspected too. However it’s not because i’m using anything special. Im using US Keyboard layout on M1 Macbook which is like most of the macbook users.

But if you see the keyboard layout on Macbook we only have ‘ we don’t have straight apostrophe here.
I attached below the exact keyboard layout used on Macbooks from official apple website. This is exactly what I have.
![image](https://github.com/GamerKingFaiz/shouldiplay/assets/34321739/ce2c1f11-ada4-4307-b70d-844ad05dfbd9)

As you can see it’s not straight apostrophe like in Windows it’s slightly slanted ‘
I would appreciate if you added a filter to ignore ‘ as its literally what pops out when i type in macbooks, can’t change it!

**Comment by GamerKingFaiz** [comment]
> Awesome except one! Duke Nukem 3D is not fixed yet

Oh good catch! It's fixed now.

> I would appreciate if you added a filter to ignore ‘ as its literally what pops out when i type in macbooks, can’t change it!

I'd like to keep the search functionality on parity with what HLTB has and as I mentioned in the previous comment, the right single quote doesn't work on HLTB either.

Doing a quick search, it seems like there might be a setting called smart quotes you can disable on Mac.  
https://discussions.apple.com/thread/252715831?answerId=255111236022#255111236022
If that doesn't work, there might be another setting that you could Google.

I don't use a Mac, so sorry I can't help much further. 😅 Workaround to this would be to just not type the apostrophe in the search.

**Comment by tejapoth** [comment]
Yeah I went down the rabbit hole after you posted about the smart quotes setting in macbooks and unfortuantely it’s an operating system thing, Apple forces it to be slanted like this ’ in words instead of straight '.

As you can see below i changed it to display as Windows style Straight apostrophe.
<img width="253" alt="image" src="https://github.com/GamerKingFaiz/shouldiplay/assets/34321739/c8efdcf6-8cac-43f2-ab86-15c20678ba53">

but that only works in quotes 'like so'. When I type the ' within a word like Luigi’s mansion it goes back to being slanted.  HLTB
<img width="1385" alt="image" src="https://github.com/GamerKingFaiz/shouldiplay/assets/34321739/9dc2c950-a258-4feb-ac8e-8fdc26e7556b">
 and SIPT
<img width="936" alt="image" src="https://github.com/GamerKingFaiz/shouldiplay/assets/34321739/32c0716e-e6f3-4bc3-910a-83d5387e00aa">

That's apple for you lol. 

Would be great if some idea pops in your head to get rid of this. I can easily not type the apostrophe but the thing is I use a chrome extension called right click context search - where i right click a word and search that word within a website like SIPT. That’s why this causes issues! As I usually browse "best switch games" and then right click that game’s name and search it on SIPT like below which causes issues with games which have apostrophes or weird symbols 😂
<img width="695" alt="image" src="https://github.com/GamerKingFaiz/shouldiplay/assets/34321739/92a4d6a0-fe83-49e9-a6f2-7fc3f8110387">
